# Generated by Django 5.1.4 on 2025-01-02 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyMovieList",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("movie_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("poster_path", models.CharField(max_length=255)),
                ("vote_average", models.FloatField()),
                ("genre_ids", models.CharField(max_length=255)),
                ("overview", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("is_liked", models.BooleanField(default=False)),
                ("is_disliked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mymovielist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
