# Generated by Django 5.1.4 on 2025-01-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymovielist",
            name="is_disliked",
        ),
        migrations.RemoveField(
            model_name="mymovielist",
            name="is_liked",
        ),
        migrations.AddField(
            model_name="mymovielist",
            name="rating",
            field=models.CharField(
                choices=[("LIKE", "Like"), ("DISLIKE", "Dislike"), ("NONE", "None")],
                default="NONE",
                max_length=7,
            ),
        ),
    ]
