# Generated by Django 5.1.4 on 2025-01-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_remove_mymovielist_is_disliked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymovielist",
            name="genre_ids",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="mymovielist",
            name="overview",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="mymovielist",
            name="poster_path",
            field=models.CharField(max_length=512),
        ),
    ]
