# Generated by Django 5.1.4 on 2025-01-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_mymovielist_genre_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymovielist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
