# Generated by Django 5.1.4 on 2025-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_mymovielist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mymovielist",
            name="vote_average",
            field=models.FloatField(null=True),
        ),
    ]
